### Conversation
# @confirmation true
# @tls.certFile /Users/tgingras/Documents/Projects/@studiowebux/restcli/requests/tls/cert.pem
# @tls.keyFile /Users/tgingras/Documents/Projects/@studiowebux/restcli/requests/tls/key.pem
GET https://jsonplaceholder.typicode.com/posts/3
