### Create Post
# @category api
# @category example
# @category create
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
  "title": "Test Post",
  "body": "This is a test - {{foo}}",
  "userId": 1
}
